### ISSUE TITLE
Scalar list (array of enum) empty when parent type uses integer @id

### ISSUE THREAD

**Issue by danielhopp** [prisma/datamodel-v1.1-feedback#18]
### datamodel.prisma
```graphql
enum Option {
  A
  B
  C
}

type Something {
  id: Int! @id
  options: [Option] @scalarList(strategy:RELATION)
}
```
### Example
```graphql
mutation ($data: SomethingCreateInput!) {
  createSomething(data: $data) {
    id
    options
  }
}
```
```javascript
{
  "data": {
    "options": { "set": ["A", "B"] }
  }
}
```
### Expected
```javascript
{
  "data": {
    "createSomething": {
      "id": 1,
       "options": [
        "A",
        "B"
      ]
    }
  }
}
```
### Actual result
```javascript
{
  "data": {
    "createSomething": {
      "id": 1,
      "options": []
    }
  }
}
```
### Annotations
* Mutation actually creates options in database, but returns empty options list
* Problem is specific to integer IDs (`id: Int! @id`), issue does not occur when using random IDs (`id: ID! @id`)
* prisma:1.31-beta, prisma:1.32-alpha
* Applies to mysql:5.7 and postgres:11.2

**Comment by danielhopp** [comment]
SQL log shows scalarList entries are actually being selected by prisma:
```graphql
query { somethings { options } }
```
```javascript
{
  "data": {
    "somethings": [
      {
        "options": []
      }
    ]
  }
}
```
```sql
SELECT 
  `default@default`.`Something_options`.`nodeId`,
  `default@default`.`Something_options`.`position`,
  `default@default`.`Something_options`.`value`
FROM
  `default@default`.`Something_options`
WHERE
  `default@default`.`Something_options`.`nodeId` IN (1);
```
```csv
'1','1000','A'
'1','2000','B'
```

**Comment by ZenSoftware** [comment]
@danielhopp Should we maybe post this in the main prisma repo?  It might get more attention and hopefully the community can come up with a workaround until a fix can be rolled out.

**Comment by danielhopp** [comment]
@ZenSoftware Yes! I just realized datamodel v1.1 already has a stable release. As I do not have permissions to transfer I created a new issue: prisma/prisma#4421
