### ISSUE TITLE
Mongodb array as embedded document

### ISSUE THREAD

**Issue by navneetgarggate6** [prisma/datamodel-v1.1-feedback#22]
I want to embedded multiple sub document (array in user for location) every thing is working flne but prisma adming giving following error

[
  {
    "message": "Cannot query field 'undefined' on type 'Query'. (line 2, column 3):\n  undefined(first: 100, skip: 0) {\n  ^",
    "locations": [
      {
        "line": 2,
        "column": 3
      }
    ]
  },
  {
    "message": "Cannot query field 'undefinedConnection' on type 'Query'. Did you mean 'usersConnection'? (line 9, column 3):\n  count: undefinedConnection {\n  ^",
    "locations": [
      {
        "line": 9,
        "column": 3
      }
    ]
  }
]

type User {
  id: ID! @id
  name: String
  location: [Location!]!
}

type Location @embedded {
  id: ID! @id
  latitude: String!
  longitude: String!
}

**Comment by navneetgarggate6** [comment]
I think i should add it in admin feedback

**Comment by janpio** [comment]
=> https://github.com/prisma/prisma-admin-feedback/issues/157
